#!/bin/bash
# Automatic installation script 
# UNTESTED!!! 

# --------------------------------------------------
# Overview of the setup
# --------------------------------------------------
# Chage hostname
# Edit .bashrc
# Edit  dnf.conf
# Update system
# Add dnf and flatpak repos
# --------------------------------------------------
# Install the following apps:
# 	git bat exa vim neofetch vlc gnome-tweaks gnome-extensions-app papirus-icon-theme android-tools openssh openssl
#	Multimedia codecs
#	Brave browser
#	VSCode
#	Etcher
#	GitHub CLI
# --------------------------------------------------
# Install Extensions using brunelli script
#	GSconnect: 1319
#	Vitals: 1460
#	Caffeine: 517
#	Appindicator support: 615
#	Extension list: 3088
#	Status area spacing: 355
#	Lock keys: 36
#	Gesture improvements: 4245
#	User themes: 19
#	Bluetooth Quick Connect: 1401 
#	Dash to Dock: 307 (UNSUPPORTED)
# --------------------------------------------------
# Enable extensions using gnome-extensions tool
#	GSConnect: gsconnect@andyholmes.github.io
#	Caffeine: caffeine@patapon.info
#	Appindicator support: appindicatorsupport@rgcjonas.gmail.com
#	Status Area Horizontal Spacing: status-area-horizontal-spacing@mathematical.coffee.gmail.com
#	Vitals: Vitals@CoreCoding.com
#	Extension list: extension-list@tu.berry
#	Lock keys: lockkeys@vaina.lt
#	Gesture improvements: gestureImprovements@gestures
#	Bluetooth Quick Connect: bluetooth-quick-connect@bjarosze.gmail.com
#	Removable Drive menu: drive-menu@gnome-shell-extensions.gcampax.github.com
#	Places menu: places-menu@gnome-shell-extensions.gcampax.github.com
#	User themes: user-theme@gnome-shell-extensions.gcampax.github.com
#	Dash to Dock: dash-to-dock@micxgx.gmail.com (UNSUPPORTED)
# --------------------------------------------------
# Restart system
# --------------------------------------------------

# Functions
check_root(){
	if [[ $USER != "root" ]]; then echo "WARNING: This script MUST be run by 'root'. Now Exiting... " 
	exit 1
	fi
}

change_hostname(){
	check_root
	hostnamectl set-hostname "ThinkPad-L450"
}

bashrc(){
tee -a ~/.bashrc > /dev/null <<EOT
export PATH="$PATH:/home/pranav/Projects/Shell-scripts"

# This is the alias command. 
# It replaces the given word in the left with the word in the right. 
# In my case, I have entered the commands which I usually type wrong and replaced it with the right command. 
# Syntax: alias WORD_TO_REPLACE = REQUIRED_WORD_TO_BE_ACTUALLY_ENTERED

# Essential aliases
alias ls=exa
alias cat=bat

# Spelling mistake aliases
alias gerp=grep
alias sduo=sudo
alias usdo=sudo
alias cler=clear
alias cls=clear
alias isntall=install
alias shscr="cd ~/Projects/Shell-scripts"
alias scr="cd ~/Projects/Shell-scripts"
EOT
}

edit_conf(){
check_root
tee -a /etc/dnf/dnf.conf > /dev/null <<EOT
Fastestmirror=true
max_parallel_downloads=20
deltarpm=true
EOT
}

add_repo(){
check_root
# Adding non-free repositories
dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
dnf install -y https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

# Adding Flatpak Repository
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

#VSCode
rpm --import https://packages.microsoft.com/keys/microsoft.asc
sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'

# Brave browser
dnf install -y dnf-plugins-core
dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/x86_64/
rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc

# Etcher
curl -1sLf 'https://dl.cloudsmith.io/public/balena/etcher/setup.rpm.sh' | sudo -E bash

# GitHub CLI
dnf install -y 'dnf-command(config-manager)'
dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
}

apps(){
check_root
# Installing apps
dnf install -y git bat exa vim neofetch vlc gnome-tweaks gnome-extensions-app papirus-icon-theme android-tools openssh openssl brave-browser code balena-etcher-electron gh
#NOTE: openssl is for GSconnect

# Installing Multimedia codecs
dnf install -y gstreamer1-plugins-{bad-\*,good-\*,base} gstreamer1-plugin-openh264 gstreamer1-libav --exclude=gstreamer1-plugins-bad-free-devel
dnf install -y lame\* --exclude=lame-devel
dnf group upgrade -y --with-optional Multimedia

# Flatpak apps
flatpak install stremio -y
}

gnome-shell-extension-installer(){
if [[ -e gnome-shell-extension-installer ]]; then return
fi

check_root
# We use a shell script (https://github.com/brunelli/gnome-shell-extension-installer) to install multiple extensions altogether.
wget -O gnome-shell-extension-installer "https://github.com/brunelli/gnome-shell-extension-installer/raw/master/gnome-shell-extension-installer"
chmod +x gnome-shell-extension-installer #Executable
sudo mv gnome-shell-extension-installer /usr/bin/ #Added to root directory, so can be accessed anywhere
}

extensions(){

# PLEASE USE runuser -l usernameHere -c 'commandHere'
# Reference: https://www.cyberciti.biz/open-source/command-line-hacks/linux-run-command-as-different-user/

# Installation of extensions first
gnome-shell-extension-installer 1319 1460 517 615 3088 355 36 4245 19 1401 #307
gnome-shell-extension-installer 1319 1460 517 615 3088 355 36 4245 19 1401 #307 #running again since it doesn't install in the first run :)

# Enabling extensions
gnome-extensions enable gsconnect@andyholmes.github.io
gnome-extensions enable caffeine@patapon.info
gnome-extensions enable appindicatorsupport@rgcjonas.gmail.com
gnome-extensions enable status-area-horizontal-spacing@mathematical.coffee.gmail.com
gnome-extensions enable Vitals@CoreCoding.com
gnome-extensions enable extension-list@tu.berry
gnome-extensions enable lockkeys@vaina.lt
gnome-extensions enable gestureImprovements@gestures
gnome-extensions enable bluetooth-quick-connect@bjarosze.gmail.com
gnome-extensions enable drive-menu@gnome-shell-extensions.gcampax.github.com
gnome-extensions enable places-menu@gnome-shell-extensions.gcampax.github.com
gnome-extensions enable user-theme@gnome-shell-extensions.gcampax.github.com
#gnome-extensions enable dash-to-dock@micxgx.gmail.com # SINCE CURRENTLY UNSUPPORTED, in Gnome 42
}

restart(){
check_root
echo "Restart the system? (y/n)"
read response
if [[ response = "y" ]]; then
	sudo reboot
else
	exit 1
fi
}

# Declared all functions till now
# Now, actually executing every function one by one :)

change_hostname
bashrc
edit_conf
add_repo
apps
gnome-shell-extension-installer
#runuser -l pranav -c "extensions" #EXTENSIONS INSTALLATION IS A BIG DEAL CURRENTLY; cannot execute the function as a user
restart


