#!/bin/bash

# --------------------------------------------------
# Overview of the setup
# --------------------------------------------------
# Check for root
# Chage hostname
# Edit .bashrc
# Edit  dnf.conf
# Update system
# Add dnf and flatpak repos
# --------------------------------------------------
# Install the following apps:
# 	git bat exa vim neofetch vlc gnome-tweaks gnome-extensions-app papirus-icon-theme android-tools openssh openssl
#	Multimedia codecs
#	Brave browser
#	VSCode
#	Etcher
#	GitHub CLI
# --------------------------------------------------
# Install Extensions using brunelli script
#	GSconnect: 1319
#	Vitals: 1460
#	Caffeine: 517
#	Appindicator support: 615
#	Extension list: 3088
#	Status area spacing: 355
#	Lock keys: 36
#	Gesture improvements: 4245
#	Dash to Dock: 307
# --------------------------------------------------
# Restart system
# --------------------------------------------------

# Functions
check_root(){
	if [[ $USER != "root" ]]; then echo "WARNING: This script MUST be run by 'root'. Now Exiting... " 
	exit 1
	fi
}

hostname(){
	hostnamectl set-hostname "ThinkPad-L450"
}

bashrc(){
tee -a ~/.bashrc > /dev/null <<EOT
export PATH="$PATH:/home/pranav/Projects/Shell-scripts"

# This is the alias command. 
# It replaces the given word in the left with the word in the right. 
# In my case, I have entered the commands which I usually type wrong and replaced it with the right command. 
# Syntax: alias WORD_TO_REPLACE = REQUIRED_WORD_TO_BE_ACTUALLY_ENTERED

# Essential aliases
alias ls=exa
alias cat=bat

# Spelling mistake aliases
alias gerp=grep
alias sduo=sudo
alias usdo=sudo
alias cler=clear
alias cls=clear
alias isntall=install
alias shscr="cd ~/Projects/Shell-scripts"
alias scr="cd ~/Projects/Shell-scripts"
EOT
}

edit_conf(){
check_root
tee -a /etc/dnf/dnf.conf > /dev/null <<EOT
Fastestmirror=true
max_parallel_downloads=20
deltarpm=true
EOT
}

add_repo(){
check_root
# Adding non-free repositories
dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
dnf install -y https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

# Adding Flatpak Repository
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

#VSCode
rpm --import https://packages.microsoft.com/keys/microsoft.asc
sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'

# Brave browser
dnf install -y dnf-plugins-core
dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/x86_64/
rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc

# Etcher
curl -1sLf 'https://dl.cloudsmith.io/public/balena/etcher/setup.rpm.sh' | sudo -E bash

# GitHub CLI
dnf install -y 'dnf-command(config-manager)'
dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
}

apps(){

# Installing apps
dnf install -y git bat exa vim neofetch vlc gnome-tweaks gnome-extensions-app papirus-icon-theme android-tools openssh openssl brave-browser code balena-etcher-electron gh
#NOTE: openssl is for GSconnect

# Installing Multimedia codecs
dnf install -y gstreamer1-plugins-{bad-\*,good-\*,base} gstreamer1-plugin-openh264 gstreamer1-libav --exclude=gstreamer1-plugins-bad-free-devel
dnf install -y lame\* --exclude=lame-devel
dnf group upgrade -y --with-optional Multimedia

# Flatpak apps
flatpak install stremio -y
}
